name: Build Run and Test Docker Container

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker container
        run: |
          # Build your Docker image (replace 'a11y-assist' and 'Dockerfile' with your image name and Dockerfile path)
          docker build -t a11y-assist .
          # Run the Docker container (adjust any options as needed)
          docker run -dit --name a11y-assist-container a11y-assist
        # Ensure the Docker container is running before running the next step
        continue-on-error: true

      - name: Run Node CLI command inside the Docker container
        run: |
          # Execute a website crawl
          docker exec -e A11Y_ASSIST_VERBOSE=1 -e GOOGLE_SAFE_BROWSING=1 -e A11Y_ASSIST_FAST_CRAWLER=1 a11y-assist-container npm run cli -- -u "${{ vars.A11Y_ASSIST_SCAN_URL }}" -c intelligent -p "${{ vars.A11Y_ASSIST_SCAN_MAX_NUM_PAGES }}" -t "${{ vars.A11Y_ASSIST_SCAN_MAX_CONCURRENCY }}" -k "${{ github.actor }}:${{ github.actor }}@users.noreply.github.com" -g yes || true

      - name: Print logs
        run: |
          docker exec a11y-assist-container sh -c 'cat /app/a11y-assist/????????-????-????-????-????????????.txt' || true

      - name: Copy Results from Docker Container
        run: docker cp a11y-assist-container:/app/a11y-assist/results ./results

      - name: Zip Results
        run: zip -r results.zip ./results

      - name: Upload Zip File
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results.zip

      - name: Cleanup Docker container
        run: |
          # Stop and remove the Docker container
          docker stop a11y-assist-container
          docker rm a11y-assist-container
